### ISSUE TITLE
fails if not using i3status

### ISSUE THREAD

**Issue by biwhite** [obestwalter/i3configger#2]
This doesn't work if you don't use i3status.  I use polybar instead so I have no i3status process running, which causes this error when running your tool:

~~~~
i3status: no process found
Traceback (most recent call last):
  File "/usr/bin/i3configger", line 11, in <module>
    load_entry_point('i3configger==0.4.3', 'console_scripts', 'i3configger')()
  File "/usr/lib/python3.6/site-packages/i3configger/main.py", line 46, in main
    ipc.StatusBar.refresh()
  File "/usr/lib/python3.6/site-packages/i3configger/ipc.py", line 74, in refresh
    subprocess.check_call(['killall', '-SIGUSR1', 'i3status'])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['killall', '-SIGUSR1', 'i3status']' returned non-zero exit status 1.
~~~~

**Comment by obestwalter** [comment]
Thanks @biwhite - I will make that optional then. Can you link to you config, so I can see how other bars are integrated?

**Comment by obestwalter** [comment]
Just released 0.4.4 which ignores problems trying to refresh i3status for now. Let me know, if it works for you now.

When I learned about what else is out there, I will integrate othe refresh methods for othe bars (or at least not fail - like now).

**Comment by biwhite** [comment]
No longer fails thanks.  Personally I use polybar, with a custom script that kills/launches it when i3 starts using exec_always to force it to restart when i3 reloads config.
I've got my dotfiles at github.com/biwhite/dotfiles if you'd like to see further.

**Comment by obestwalter** [comment]
Thanks. I will have a look :)

**Comment by ILMostro** [comment]
hmm...I wonder if this is the same issue with i3bar + i3status.  After config changes are made in the `~/.config/i3status/config` file, even after i3 restarts, the changes are not reflected in i3status.

```
# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}
```
